const mongoose=require('mongoose')

const ProductSchema=new mongoose.Schema({
    productName:{
        type:String,
        required:true,
        trim:true
    },
    productTypeId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        trim:true,
        ref:'ProductType'
    },
    productSubTypeId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        trim:true,
        ref:'ProductType'
    },
    productBrandId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        trim:true,
        ref:'ProductType'
    }
    ,
    productQuantity:{
        type:Number,
        required:true,
        trim:true
    },
    productSizes:[{
        size:{
            type:String,
            trim:true
        },
        count:{
            type:Number,
            trim:true
        }
    }],
    productDescription:{
        type:String,
        required:true,
        trim:true
    },
    productImage:{
        type:Buffer
    },
    productImages:[{
        type:Buffer
    }],
    createdBy:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        trim:true,
        ref:"AdminEntry"
    },
    updatedBy:[{
        adminId:{
            type:mongoose.Schema.Types.ObjectId
        }
    }]
})

const Product=mongoose.model('Product',ProductSchema)
module.exports=Product
